import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

import { renderDailyDigestEmail } from "@astreex/email"
import { describe, expect, it, vi } from "vitest"

import {
  readEmailCompositionConfiguration,
  readResendDeliveryConfiguration,
  readResendWebhookConfiguration,
} from "../convex/email/config"
import {
  RESEND_API_BASE_URL,
  createResendClient,
} from "../convex/integrations/resend"
import {
  dailyDigestIdempotencyKey,
  planDailyDigest,
} from "../convex/lib/dailyDigest"
import {
  verifyResendEmailWebhook,
  type ResendEmailEventType,
} from "../convex/lib/resendWebhook"
import {
  createDailyDigestEmailModel,
  rankDigestMentions,
  rankableDigestCandidate,
  type DigestMentionCandidate,
} from "../convex/digest/model"
import { usageWarningThresholdsToEnqueue } from "../convex/ingestion/model"

function fixture(name: string): string {
  return readFileSync(
    fileURLToPath(new URL(`./fixtures/email/${name}`, import.meta.url)),
    "utf8",
  )
}

type DigestFixture = {
  localDate: string
  mentions: DigestMentionCandidate[]
}

type UsageFixture = {
  expected: Array<80 | 100>
  mentionLimit: number
  mentionsUsed: number
  sent100At?: number
  sent80At?: number
}

const digestFixture = JSON.parse(fixture("digest-cases.json")) as DigestFixture
const usageFixture = JSON.parse(
  fixture("usage-thresholds.json"),
) as UsageFixture[]

describe("daily digest orchestration model", () => {
  it("uses exactly one workspace/local-date period", () => {
    const expected = "daily-digest:workspace-fixture:2026-07-25"
    expect(
      dailyDigestIdempotencyKey({
        localDate: "2026-07-25",
        workspaceId: "workspace-fixture",
      }),
    ).toBe(expected)
    expect(
      planDailyDigest({
        alreadyRecorded: false,
        mentions: digestFixture.mentions.map(rankableDigestCandidate),
        schedule: { hour: 9, minute: 0, timeZone: "UTC" },
        scheduledFor: Date.parse("2026-07-26T09:00:00.000Z"),
        workspaceId: "workspace-fixture",
      }).idempotencyKey,
    ).toBe(expected)
  })

  it("ranks fixture mentions by deterministic engagement and stable tie breakers", () => {
    expect(
      rankDigestMentions(digestFixture.mentions, 3).map(
        ({ candidate, engagementScore, rank }) => ({
          engagementScore,
          id: candidate.id,
          rank,
        }),
      ),
    ).toEqual([
      { engagementScore: 22, id: "reddit:fixture-1", rank: 1 },
      { engagementScore: 11, id: "hacker_news:42000001", rank: 2 },
      { engagementScore: 8, id: "x:1000000000000000001", rank: 3 },
    ])
  })

  it("renders full category counts and only deterministic top canonical links", async () => {
    const ranked = rankDigestMentions(digestFixture.mentions, 2)
    const emailModel = createDailyDigestEmailModel({
      mentions: digestFixture.mentions,
      topMentionIds: ranked.map(({ candidate }) => candidate.id),
    })
    const rendered = await renderDailyDigestEmail({
      astreexUrl: "https://app.example.com/app/mentions",
      counts: emailModel.counts,
      localDate: digestFixture.localDate,
      topMentions: emailModel.topMentions,
      workspaceName: "Fixture Workspace",
    })

    expect(emailModel.counts.total).toBe(3)
    expect(emailModel.counts.byCategory).toMatchObject({
      Bug: 1,
      Praise: 1,
      Question: 1,
    })
    expect(emailModel.topMentions.map(({ url }) => url)).toEqual([
      "https://www.reddit.com/r/startups/comments/fixture/astreex/",
      "https://news.ycombinator.com/item?id=42000001",
    ])
    expect(rendered.html).toContain(
      "https://news.ycombinator.com/item?id=42000001",
    )
    expect(rendered.html).not.toContain(
      "https://x.com/i/web/status/1000000000000000001",
    )
    expect(rendered.html.toLowerCase()).not.toContain("generated by ai")
  })

  it("does not create an outbox decision for an empty local day", () => {
    expect(
      planDailyDigest({
        alreadyRecorded: false,
        mentions: [],
        schedule: { hour: 9, minute: 0, timeZone: "UTC" },
        scheduledFor: Date.parse("2026-07-26T09:00:00.000Z"),
        workspaceId: "workspace-fixture",
      }),
    ).toMatchObject({ kind: "skipped_empty", runStatus: "skipped_empty" })
  })
})

describe("Resend HTTP integration", () => {
  it("POSTs /emails with application and provider idempotency", async () => {
    const responseFixture = JSON.parse(
      fixture("resend-send-success.json"),
    ) as unknown
    const fetchMock = vi.fn(
      async (input: RequestInfo | URL, init?: RequestInit) => {
        expect(String(input)).toBe(`${RESEND_API_BASE_URL}/emails`)
        expect(init?.method).toBe("POST")
        expect(init?.headers).toMatchObject({
          Authorization: "Bearer re_fixture_secret",
          "Content-Type": "application/json",
          "Idempotency-Key": "email:daily-digest:workspace-fixture:2026-07-25",
        })
        expect(JSON.parse(String(init?.body))).toEqual({
          from: "Astreex <notifications@example.com>",
          html: "<p>Fixture digest</p>",
          reply_to: "support@example.com",
          subject: "Fixture digest",
          text: "Fixture digest",
          to: ["owner@example.com"],
        })
        return new Response(JSON.stringify(responseFixture), { status: 200 })
      },
    )

    await expect(
      createResendClient({
        apiKey: "re_fixture_secret",
        fetch: fetchMock as typeof fetch,
      }).sendEmail({
        from: "Astreex <notifications@example.com>",
        html: "<p>Fixture digest</p>",
        idempotencyKey: "email:daily-digest:workspace-fixture:2026-07-25",
        replyTo: "support@example.com",
        subject: "Fixture digest",
        text: "Fixture digest",
        to: ["owner@example.com"],
      }),
    ).resolves.toEqual(responseFixture)
    expect(fetchMock).toHaveBeenCalledOnce()
  })

  it("rejects undocumented success response fields through Zod", async () => {
    const fetchMock = vi.fn(
      async () =>
        new Response(JSON.stringify({ id: "email-fixture", invented: true }), {
          status: 200,
        }),
    )

    await expect(
      createResendClient({
        apiKey: "re_fixture_secret",
        fetch: fetchMock as typeof fetch,
      }).sendEmail({
        from: "Astreex <notifications@example.com>",
        html: "<p>Fixture digest</p>",
        idempotencyKey: "email:fixture-invalid-response",
        subject: "Fixture digest",
        to: ["owner@example.com"],
      }),
    ).rejects.toMatchObject({ code: "INVALID_RESPONSE" })
  })

  it("aborts timed-out sends with a typed retryable error", async () => {
    const fetchMock = vi.fn(
      (_input: RequestInfo | URL, init?: RequestInit) =>
        new Promise<Response>((_resolve, reject) => {
          init?.signal?.addEventListener("abort", () => {
            reject(new DOMException("aborted", "AbortError"))
          })
        }),
    )

    await expect(
      createResendClient({
        apiKey: "re_fixture_secret",
        fetch: fetchMock as typeof fetch,
        timeoutMs: 1,
      }).sendEmail({
        from: "Astreex <notifications@example.com>",
        html: "<p>Fixture digest</p>",
        idempotencyKey: "email:fixture-timeout",
        subject: "Fixture digest",
        to: ["owner@example.com"],
      }),
    ).rejects.toMatchObject({
      code: "REQUEST_TIMEOUT",
      retryable: true,
    })
  })

  it("reports blocked configuration without returning secret values", () => {
    expect(readResendDeliveryConfiguration({})).toEqual({
      missing: ["RESEND_API_KEY"],
      provider: "resend",
      state: "provider_unconfigured",
    })
    expect(readResendWebhookConfiguration({})).toEqual({
      missing: ["RESEND_WEBHOOK_SECRET"],
      provider: "resend",
      state: "provider_unconfigured",
    })
    expect(readEmailCompositionConfiguration({})).toEqual({
      missing: ["APP_URL", "RESEND_FROM_EMAIL"],
      provider: "resend",
      state: "provider_unconfigured",
    })
    expect(
      readResendWebhookConfiguration({
        RESEND_WEBHOOK_SECRET: "  whsec_fixture  ",
      }),
    ).toEqual({ state: "configured", webhookSecret: "whsec_fixture" })
  })
})

describe("Resend Svix webhook contract", () => {
  it("verifies documented Svix headers and projects only stored delivery fields", () => {
    const providerEvent = JSON.parse(
      fixture("resend-webhook-delivered.json"),
    ) as unknown
    const verify = vi.fn().mockReturnValue(providerEvent)

    expect(
      verifyResendEmailWebhook({
        eventId: "msg_fixture_svix_1",
        payload: fixture("resend-webhook-delivered.json"),
        signature: "v1,fixture-signature",
        timestamp: "1785060000",
        verifier: { webhooks: { verify } },
        webhookSecret: "whsec_fixture",
      }),
    ).toEqual({
      createdAt: Date.parse("2026-07-26T10:00:00.000Z"),
      eventId: "msg_fixture_svix_1",
      providerMessageId: "49a3999c-0ce1-4ea6-ab68-afcd6dc2e794",
      type: "email.delivered",
    })
    expect(verify).toHaveBeenCalledWith({
      headers: {
        id: "msg_fixture_svix_1",
        signature: "v1,fixture-signature",
        timestamp: "1785060000",
      },
      payload: fixture("resend-webhook-delivered.json"),
      webhookSecret: "whsec_fixture",
    })
  })

  it("ignores verified event families not persisted by the outbound email schema", () => {
    const verify = vi.fn().mockReturnValue({
      created_at: "2026-07-26T10:00:00.000Z",
      data: { email_id: "received-email-fixture" },
      type: "email.received" satisfies Exclude<
        "email.received",
        ResendEmailEventType
      >,
    })

    expect(
      verifyResendEmailWebhook({
        eventId: "msg_fixture_svix_received",
        payload: "{}",
        signature: "v1,fixture-signature",
        timestamp: "1785060000",
        verifier: { webhooks: { verify } },
        webhookSecret: "whsec_fixture",
      }),
    ).toBeNull()
  })
})

describe("billing-cycle usage notification thresholds", () => {
  it("uses only fixture-backed 80% and 100% notifications once per cycle", () => {
    for (const testCase of usageFixture) {
      expect(usageWarningThresholdsToEnqueue(testCase)).toEqual(
        testCase.expected,
      )
    }
  })
})
